prompts:
  - file://prompts/prompt_1_null.txt
  - file://prompts/prompt_2_empty.txt

providers:
  - id: openrouter:anthropic/claude-3.5-haiku
    config:
      temperature: 0.0
  - id: google:gemini-2.5-flash
    config:
      temperature: 0.0
  - id: xai:grok-4-fast-non-reasoning
    config:
      temperature: 0.0
  - id: openai:gpt-5-mini-2025-08-07
    config:
      temperature: 0.0
    

tests:
  - file://tests/is_json.yaml